export const CART_ACTIONS = {
	ADD_TO_CART: 'ADD_TO_CART',
	DECREMENT_QUANTITY: 'DECREMENT_QUANTITY',
	DELETE_FROM_CART: 'DELETE_FROM_CART',
	INCREMENT_QUANTITY: 'INCREMENT_QUANTITY',
	EMPTY_CART: 'EMPTY_CART'
};
